AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TopicName:
    Type: String
    Description: "[REQUIRED] The name of SNS topic."
  AlarmName:
    Type: String
    Description: "[optional] The name of CloudWatch alarm for SNS topic."
  TemplateBucketName:
    Type: String
    Description: "[optional] The name of template's S3 bucket."

Conditions:
  UseAlarmName: !Not [!Equals [!Ref AlarmName, ""]]
  UseNotificationLogging: !Not [!Equals [!Ref TemplateBucketName, ""]]

Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref TopicName
      TopicName: !Ref TopicName
  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !If
        - UseAlarmName
        - !Ref AlarmName
        - !Sub
          - ${Name}-alarm
          - { Name: !Ref TopicName }
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: TopicName
          Value: !GetAtt Topic.TopicName
      EvaluationPeriods: 1
      MetricName: NumberOfMessagesPublished
      Namespace: AWS/SNS
      Period: 60
      Statistic: Sum
      Threshold: 1
  
  SnsNotificationLoggingStack:
    Type: AWS::CloudFormation::Stack
    Condition: UseNotificationLogging
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.amazonaws.com/cloudformation-templates/sns/sns-notification-logging.yaml # https://github.com/marcus16-kang/cloudformation-templates/blob/main/sns/sns-notification-logging.yaml
      # Parameters:
      #   RoleName: SNS_NOTIFICATION_LOGGING_ROLE_NAME
      #   FunctionName: SNS_NOTIFICATION_LOGGING_FUNCTION_NAME
      #   LoggingConfiguration: SNS_NOTIFICATION_LOGGING_CONFIGURATION
      TimeoutInMinutes: 10
  Subscription:
    Type: AWS::SNS::Subscription
    Condition: UseNotificationLogging
    DependsOn: SnsNotificationLoggingStack
    Properties:
      Endpoint: !GetAtt SnsNotificationLoggingStack.Outputs.FunctionArn
      Protocol: lambda
      TopicArn: !Ref Topic
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Condition: UseNotificationLogging
    DependsOn: SnsNotificationLoggingStack
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SnsNotificationLoggingStack.Outputs.FunctionArn
      Principal: sns.amazonaws.com
      SourceArn: !Ref Topic

Outputs:
  TopicArn:
    Value: !Ref Topic
  AlarmArn:
    Value: !Ref Alarm
