AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ### Stack Configuration
  ProjectName:
    Type: String
    Description: "[REQUIRED] The name of this project."
  
  ### Repository Configuration - General
  RepositoryName:
    Type: String
    Description: "[REQUIRED] The name of ECR repository."
  
  ### Repository Configuration - Encryption
  EncryptionType:
    Type: String
    Description: "`KMS`(default) or `AES256` | [REQUIRED] The type of ECR repository encryption."
    AllowedValues:
      - AES256
      - KMS
    Default: KMS
  
  KmsKey:
    Type: String
    Description: "[optional] The alias, ID, or ARN of KMS key for ECR repository encryption."
    Default: alias/aws/ecr
  
  ### Repository Configuration - Scanning
  Scanning:
    Type: String
    Description: "`true`(default) or `false` | [REQUIRED] Enable or disable image scanning."
    AllowedValues:
      - "false"
      - "true"
    Default: "true"
  
  ### Repository Configuration - Immutable
  Immutable:
    Type: String
    Description: "`IMMUTABLE`(default) or `MUTABLE` | [REQUIRED] Mutable of immutable ECR repository's images."
    AllowedValues:
      - MUTABLE
      - IMMUTABLE
    Default: IMMUTABLE

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Configuration
        Parameters:
          - ProjectName
      
      - Label:
          default: Repository Configuration - General
        Parameters:
          - RepositoryName

      - Label:
          default: Repository Configuration - Encryption
        Parameters:
          - EncryptionType
          - KmsKey
      
      - Label:
          default: Repository Configuration - Scanning
        Parameters:
          - Scanning

      - Label:
          default: Repository Configuration - Immutable
        Parameters:
          - Immutable

Conditions:
  UseKmsKey: !Equals [!Ref EncryptionType, "KMS"]

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties: 
      EncryptionConfiguration: 
        EncryptionType: !Ref EncryptionType     # AES256(SSE-S3) or KMS(SSE-KMS)
        KmsKey: !If                             # KMS alias, key ID, or full ARN of AWS KMS KEY
          - UseKmsKey
          - !Ref KmsKey
          - !Ref AWS::NoValue
      ImageScanningConfiguration: 
        ScanOnPush: !Ref Scanning               # true of false
      ImageTagMutability: !Ref Immutable        # MUTABLE or IMMUTABLE
      # LifecyclePolicy: 
      #   LifecyclePolicyText: '{"rules": []}'  # JSON type
      #   RegistryId: !Ref AWS::AccountId       # or Other AWS Account ID
      RepositoryName: !Ref RepositoryName
      # RepositoryPolicyText: 
      #   Version: "2012-10-17"
      #   Statement: 
      #     - 
      #       Sid: AllowPushPull
      #       Effect: Allow
      #       Principal: 
      #         AWS: 
      #           - "arn:aws:iam::123456789012:user/Bob"
      #           - "arn:aws:iam::123456789012:user/Alice"
      #       Action: 
      #         - "ecr:GetDownloadUrlForLayer"
      #         - "ecr:BatchGetImage"
      #         - "ecr:BatchCheckLayerAvailability"
      #         - "ecr:PutImage"
      #         - "ecr:InitiateLayerUpload"
      #         - "ecr:UploadLayerPart"
      #         - "ecr:CompleteLayerUpload"
      Tags: 
        - Key: project
          Value: !Ref ProjectName