version: 0.0

os: linux

files:
  - source: /
    destination: /app/

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 10
      runas: 30
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 30
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 120
      runas: root