version: 0.0

Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "serverless-function"
        Alias: "prod"
        CurrentVersion: "CURRENT_VERSION"
        TargetVersion: "TARGET_VERSION"

# Hooks:
#   - BeforeAllowTraffic: "serverless-deploy-before-traffic-function"
#   - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"
