AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EfsName:
    Type: String
  EfsAccessPointName:
    Type: String

Resources:
  EfsAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      AccessPointTags:
        - Key: Name
          Value: !Ref EfsAccessPointName
        # - Key: String
        #   Value: String
      FileSystemId: !Ref EfsFileSystem                    # [REQUIRED] file system id
      # PosixUser:
      #   Gid: "1234"
      #   Uid: "1234"
      #   SecondaryGids:
      #     - "1344"
      #     - "1452"
      # RootDirectory:
      #   CreationInfo:
      #     OwnerGid: "708798"
      #     OwnerUid: "7987987"
      #     Permissions: "0755"
      #   Path: "/testcfn/abc"

  EfsFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      # AvailabilityZoneName:                             # Used to create a file system that uses ONE ZONE STORAGE CLASSES.
      BackupPolicy:
        Status: ENABLED                                   # `ENABLED`(default) or `DISABLED`
      BypassPolicyLockoutSafetyCheck: false               # `false`(default) or `true`
      Encrypted: true                                     # `true`(default) or `false`
      # FileSystemPolicy:                                 # https://marcus16-kang.github.io/aws-resources-example/Storage/EFS/01-efs-policies/
      #   Version: '2012-10-17'
      #   Statement:
      #     - Effect: Allow
      #       Principal:
      #         AWS: "*"
      #       Action:
      #       - elasticfilesystem:ClientRootAccess
      #       - elasticfilesystem:ClientWrite
      #       - elasticfilesystem:ClientMount
      #       Condition:
      #         Bool:
      #           elasticfilesystem:AccessedViaMountTarget: 'true'
      #     - Effect: Deny
      #       Principal:
      #         AWS: "*"
      #       Action: "*"
      #       Condition:
      #         Bool:
      #           aws:SecureTransport: 'false'
      FileSystemTags:
        - Key: Name
          Value: !Ref EfsName
      #   - Key: String
      #     Value: String
      # KmsKeyId:                                         # KMS alias, key ID, or full ARN of AWS KMS KEY
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS                   # nothing, `AFTER_1_DAY`, `AFTER_7_DAYS`, `AFTER_14_DAYS`, `AFTER_30_DAYS`, `AFTER_60_DAYS`, `AFTER_90_DAYS`
        - TransitionToPrimaryStorageClass: AFTER_1_ACCESS # nothing, `AFTER_1_ACCESS`
      PerformanceMode: generalPurpose                     # `generalPurpose`(default) or `maxIO` if `ThroughputMode` is set to `bursting` or `provisioned`
      # ProvisionedThroughputInMibps: 1024                # Required if `ThroughputMode` is set to `provisioned`
      ThroughputMode: bursting                            # `bursting`(default), `elastic` or `provisioned`

Outputs:
  EfsFileSystemId:
    Value: !Ref EfsFileSystem
  EfsFileSystemDns:
    Value: !Sub
      - ${EfsId}.efs.${Region}.amazonaws.com
      - EfsId: !Ref EfsFileSystem
        Region: !Ref AWS::Region