AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ### Stack Configuration
  ProjectName:
    Type: String
    Description: "[REQUIRED] The name of this project."
  
  ### Subnet Group Configuration
  SubnetGroupName:
    Type: String
    Description: "[REQUIRED] Name of database subnet group"

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "[REQUIRED] List of database subnet ids."
  
  ### Parameter Group Configuration
  ClusterParameterGroupName:
    Type: String
    Description: "[REQUIRED] Name of database cluster parameter group."
  
  ParameterGroupName:
    Type: String
    Description: "[REQUIRED] Name of database parameter group."
  
  ### Global Cluster Configuration
  GlobalClusterIdentifier:
    Type: String
    Description: "[REQUIRED] Identifier(name) used for global database cluster."
    AllowedPattern: "^[a-zA-Z]{1}(?:-?[a-zA-Z0-9]){0,62}$"
  
  ### Cluster Configuration - General
  ClusterIdentifier:
    Type: String
    Description: "[REQUIRED] Identifier(name) used for database cluster."
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9-]{0,62}[^-]$
  
  EngineVersion:
    Type: String
    Description: "[REQUIRED] EngineVersion for database. (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-engineversion)"
    AllowedValues:
      - "8.0.mysql_aurora.3.01.0"
      - "8.0.mysql_aurora.3.01.1"
      - "8.0.mysql_aurora.3.02.0"
      - "8.0.mysql_aurora.3.02.1"
      - "8.0.mysql_aurora.3.02.2"
      - "8.0.mysql_aurora.3.02.3"
      - "8.0.mysql_aurora.3.03.0"
      - "8.0.mysql_aurora.3.03.1"
  
  KmsKeyId:
    Type: String
    Description: "[optional] Arn of kms key for database cluster. (If don't specify this property, use default key.)"
    Default: ""
  
  DeletionProtection:
    Type: String
    Description: "[optional] State for database deletion protection."
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
  
  ### Cluster Configuration - Network
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "[REQUIRED] ID of database vpc."
  
  Port:
    Type: Number
    Description: "[REQUIRED] Port number for database instance."
    Default: "3306"
  
  CreateSecurityGroup:
    Type: String
    Description: "[REQUIRED] Create a new security group or using existed security group."
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"
  
  SecurityGroupNameOrId:
    Type: String
    Description: "[REQUIRED] New security group name or existed security group id."
  
  ### Cluster Configuration - Capacity
  MinCapacity:
    Type: Number
    Description: "[REQUIRED] Min capacity of serverless cluster. (0.5 ~ 128)"
    MinValue: "0.5"
    MaxValue: "128"
  
  MaxCapacity:
    Type: Number
    Description: "[REQUIRED] Max capacity of serverless cluster. (1 ~ 128)"
    MinValue: "1"
    MaxValue: "128"
  
  ### Instance Configuration
  Instance1Identifier:
    Type: String
    Description: "[REQUIRED] Identifier(name) used for database instance 1 (maybe writer)"
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9-]{0,62}[^-]$
  
  Instance2Identifier:
    Type: String
    Description: "[REQUIRED] Identifier(name) used for database instance 2 (maybe reader)"
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9-]{0,62}[^-]$
  
  MonitoringRoleName:
    Type: String
    Description: "[REQUIRED] Name of database monitoring iam role."
    Default: RDSMonitoringRole

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Configuration
        Parameters:
          - ProjectName
      
      - Label:
          default: Subnet Group Configuration
        Parameters:
          - SubnetGroupName
          - Subnets
      
      - Label:
          default: Parameter Group Configuration
        Parameters:
          - ClusterParameterGroupName
          - ParameterGroupName
      
      - Label:
          default: Global Cluster Configuration
        Parameters:
          - GlobalClusterIdentifier
      
      - Label:
          default: Cluster Configuration - General
        Parameters:
          - ClusterIdentifier
          - EngineVersion
          - KmsKeyId
          - DeletionProtection
      
      - Label:
          default: Cluster Configuration - Network
        Parameters:
          - VpcId
          - Port
          - CreateSecurityGroup
          - SecurityGroupNameOrId
      
      - Label:
          default: Cluster Configuration - Capacity
        Parameters:
          - MinCapacity
          - MaxCapacity
      
      - Label:
          default: Instance Configuration
        Parameters:
          - InstanceClass
          - Instance1Identifier
          - Instance2Identifier
          - MonitoringRoleName

Conditions:
  CreateNewSecurityGroup: !Equals [!Ref CreateSecurityGroup, "Yes"]
  UseCmk: !Not [!Equals [!Ref KmsKeyId, ""]]

Resources:
  MonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - monitoring.rds.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
      RoleName: !Ref MonitoringRoleName
      Tags:
        - Key: project
          Value: !Ref ProjectName
  
  ClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      DBClusterParameterGroupName: !Ref ClusterParameterGroupName
      Description: !Ref ClusterParameterGroupName
      Family: aurora-mysql8.0
      Parameters:
        time_zone: UTC                                    # MySQL family
      Tags:
        - Key: project
          Value: !Ref ProjectName
  
  ParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      DBParameterGroupName: !Ref ParameterGroupName
      Description: !Ref ParameterGroupName
      Family: aurora-mysql8.0
      # Parameters:
      Tags:
        - Key: project
          Value: !Ref ProjectName
  
  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Ref SubnetGroupName
      DBSubnetGroupDescription: !Ref SubnetGroupName
      SubnetIds: !Ref Subnets
      Tags:
        - Key: project
          Value: !Ref ProjectName
  
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateNewSecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupNameOrId
      GroupName: !Ref SecurityGroupNameOrId
      SecurityGroupEgress: []                               # any traffic deny is best practice
      Tags:
        - Key: Name
          Value: !Ref SecurityGroupNameOrId
        - Key: project
          Value: !Ref ProjectName
      VpcId: !Ref VpcId
  
  Cluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterParameterGroupName: !Ref ClusterParameterGroup
      Engine: aurora-mysql
      EngineVersion: !Ref EngineVersion
      GlobalClusterIdentifier: !Ref GlobalClusterIdentifier
      DBClusterIdentifier: !Ref ClusterIdentifier
      DBSubnetGroupName: !Ref SubnetGroupName
      DeletionProtection: !Ref DeletionProtection           # `false`(default) or `true`
      EnableCloudwatchLogsExports: [audit, error, general, slowquery]
      KmsKeyId: !If
        - UseCmk
        - !Ref KmsKeyId
        - alias/aws/rds
      NetworkType: IPV4                                     # `IPV4` or `DUAL`
      Port: !Ref Port
      PreferredBackupWindow: 01:00-01:30                    # default
      PreferredMaintenanceWindow: Mon:01:30-Mon:02:00       # default
      RestoreType: full-copy                                # `full-copy` or `copy-on-write`
      ServerlessV2ScalingConfiguration:
        MinCapacity: !Ref MinCapacity
        MaxCapacity: !Ref MaxCapacity
      StorageEncrypted: true                                # `true`(default) or `false`
      Tags:
        - Key: project
          Value: !Ref ProjectName
      VpcSecurityGroupIds:
        - !If
          - CreateNewSecurityGroup
          - !GetAtt SecurityGroup.GroupId
          - !Ref SecurityGroupNameOrId
  
  Instance1:                                           # (maybe writer instance)
    Type: AWS::RDS::DBInstance
    Properties:
      AutoMinorVersionUpgrade: true                         # `true`(default) or `false`
      Engine: aurora-mysql
      DBClusterIdentifier: !Ref Cluster
      DBInstanceIdentifier: !Ref Instance1Identifier
      DBParameterGroupName: !Ref ParameterGroup
      PubliclyAccessible: false                             # `false`(default) or `true`
      DBInstanceClass: db.serverless
      EnablePerformanceInsights: true                       # `true`(default) or `false`
      MonitoringInterval: 60                                # `0`, `1`, `5`, `10`, `15`, `30`, `60`(default)
      MonitoringRoleArn: !GetAtt MonitoringRole.Arn
      PerformanceInsightsKMSKeyId: !If                      # KMS alias, key ID, or full ARN of AWS KMS KEY
        - UseCmk
        - !Ref KmsKeyId
        - alias/aws/rds
      PerformanceInsightsRetentionPeriod: 7                 # `7`(default). Valid values are 7 to 731(2 years)
      PromotionTier: 1                                      # `0`(default, because this instance is writer). Valid values are 0 to 15
  
  Instance2:                                           # (maybe reader instance)
    Type: AWS::RDS::DBInstance
    Properties:
      AutoMinorVersionUpgrade: true                         # `true`(default) or `false`
      Engine: aurora-mysql
      DBClusterIdentifier: !Ref Cluster
      DBInstanceIdentifier: !Ref Instance2Identifier
      DBParameterGroupName: !Ref ParameterGroup
      PubliclyAccessible: false                             # `false`(default) or `true`
      DBInstanceClass: db.serverless
      EnablePerformanceInsights: true                       # `true`(default) or `false`
      MonitoringInterval: 60                                # `0`, `1`, `5`, `10`, `15`, `30`, `60`(default)
      MonitoringRoleArn: !GetAtt MonitoringRole.Arn
      PerformanceInsightsKMSKeyId: !If                      # KMS alias, key ID, or full ARN of AWS KMS KEY
        - UseCmk
        - !Ref KmsKeyId
        - alias/aws/rds
      PerformanceInsightsRetentionPeriod: 7                 # `7`(default). Valid values are 7 to 731(2 years)
      PromotionTier: 2                                      # `1`(default, because this instance is first reader). Valid values are 0 to 15