AWSTemplateFormatVersion: "2010-09-09"

Description: Addons(core-dns, kube-proxy, vpc-cni) for EKS cluster's resources.

Parameters:
  ClusterName:
    Type: String
    Description: "[REQUIRED] The name of EKS cluster."
  
  ClusterOidcProvider:
    Type: String
    Description: "[REQUIRED] The IAM OIDC Provider for EKS cluster."

  ClusterOidcIssuerUrl:
    Type: String
    Description: "[REQUIRED] The OIDC Issuer URL of EKS cluster."

  VpcCniRoleName:
    Type: String
    Description: "[optional] The name of vpc-cni's IAM Role."
    Default: ""
  
  EbsCsiDriverRoleName:
    Type: String
    Description: "[optional] The name of aws-ebs-csi-driver's IAM Role."
    Default: ""
  
  ServiceAccountRoleConfigArn:
    Type: String
    Description: "[REQUIRED] The ARN of ServiceAccountRoleConfigFunction."
  
  ProjectName:
    Type: String
    Description: "[REQUIRED] The name of this project."

Conditions:
  UseVpcCniRoleName: !Not [!Equals [!Ref VpcCniRoleName, ""]]

  UseEbsCsiDriverRoleName: !Not [!Equals [!Ref EbsCsiDriverRoleName, ""]]

Resources:
  ### core-dns
  CoreDnsAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: coredns
      ClusterName: !Ref ClusterName
      ResolveConflicts: OVERWRITE

  ### kube-proxy
  KubeProxyAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: kube-proxy
      ClusterName: !Ref ClusterName
      ResolveConflicts: OVERWRITE

  ### vpc-cni
  VpcCniRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref ClusterOidcProvider
            Action:
              - "sts:AssumeRoleWithWebIdentity"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      RoleName: !If
        - UseVpcCniRoleName
        - !Ref VpcCniRoleName
        - !Sub "${ClusterName}-vpc-cni-role"
      Tags:
        - Key: Name
          Value: !If
            - UseVpcCniRoleName
            - !Ref VpcCniRoleName
            - !Sub "${ClusterName}-vpc-cni-role"
        - Key: project
          Value: !Ref ProjectName

  VpcCniRoleConfig:
    Type: Custom::ServiceAccountRoleConfig
    Properties:
      ServiceToken: !Ref ServiceAccountRoleConfigArn
      RoleName: !Ref VpcCniRole
      OidcIssuerUrl: !Ref ClusterOidcIssuerUrl
      OidcArn: !Ref ClusterOidcProvider
      Namespace: kube-system
      ServiceAccount: aws-node

  VpcCniAddon:
    Type: AWS::EKS::Addon
    DependsOn: VpcCniRoleConfig
    Properties:
      AddonName: vpc-cni
      ClusterName: !Ref ClusterName
      ResolveConflicts: OVERWRITE
      ServiceAccountRoleArn: !GetAtt VpcCniRole.Arn

  ### aws-ebs-csi-driver
  EbsCsiDriverRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref ClusterOidcProvider
            Action:
              - "sts:AssumeRoleWithWebIdentity"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
      RoleName: !If
        - UseEbsCsiDriverRoleName
        - !Ref EbsCsiDriverRoleName
        - !Sub "${ClusterName}-ebs-csi-driver-role"
      Tags:
        - Key: Name
          Value: !If
            - UseEbsCsiDriverRoleName
            - !Ref EbsCsiDriverRoleName
            - !Sub "${ClusterName}-ebs-csi-driver-role"
        - Key: project
          Value: !Ref ProjectName
  
  EbsCsiDriverRoleConfig:
    Type: Custom::ServiceAccountRoleConfig
    Properties:
      ServiceToken: !Ref ServiceAccountRoleConfigArn
      RoleName: !Ref EbsCsiDriverRole
      OidcIssuerUrl: !Ref ClusterOidcIssuerUrl
      OidcArn: !Ref ClusterOidcProvider
      Namespace: kube-system
      ServiceAccount: ebs-csi-controller-sa

  EbsCsiDriverAddon:
    Type: AWS::EKS::Addon
    DependsOn: EbsCsiDriverRoleConfig
    Properties:
      AddonName: aws-ebs-csi-driver
      ClusterName: !Ref ClusterName
      ResolveConflicts: OVERWRITE
      ServiceAccountRoleArn: !GetAtt EbsCsiDriverRole.Arn