AWSTemplateFormatVersion: "2010-09-09"

Description: AWS EFS CSI Driver for EKS cluster.

Parameters:
  ClusterName:
    Type: String
    Description: "[REQUIRED] The name of EKS cluster."
  
  ClusterOidcProvider:
    Type: String
    Description: "[REQUIRED] The IAM OIDC Provider for EKS cluster."

  ClusterOidcIssuerUrl:
    Type: String
    Description: "[REQUIRED] The OIDC Issuer URL of EKS cluster." 
  
  EfsCsiDriverRoleName:
    Type: String
    Description: "[optional] The name of EFS CSI Driver's IAM Role."
    Default: ""
  
  ServiceAccountRoleConfigArn:
    Type: String
    Description: "[REQUIRED] The ARN of ServiceAccountRoleConfigFunction."
  
  ProjectName:
    Type: String
    Description: "[REQUIRED] The name of this project."

Conditions:
  UseEfsCsiDriverRoleName:
    !Not [!Equals [!Ref EfsCsiDriverRoleName, ""]]

Mappings:
  EfsCsiDriverRepositoryMap:
    af-south-1:
      repository: 877085696533.dkr.ecr.af-south-1.amazonaws.com
    ap-east-1:
      repository: 800184023465.dkr.ecr.ap-east-1.amazonaws.com
    ap-northeast-1:
      repository: 602401143452.dkr.ecr.ap-northeast-1.amazonaws.com
    ap-northeast-2:
      repository: 602401143452.dkr.ecr.ap-northeast-2.amazonaws.com
    ap-northeast-3:
      repository: 602401143452.dkr.ecr.ap-northeast-3.amazonaws.com
    ap-south-1:
      repository: 602401143452.dkr.ecr.ap-south-1.amazonaws.com
    ap-southeast-1:
      repository: 602401143452.dkr.ecr.ap-southeast-1.amazonaws.com/
    ap-southeast-2:
      repository: 602401143452.dkr.ecr.ap-southeast-2.amazonaws.com
    ap-southeast-3:
      repository: 296578399912.dkr.ecr.ap-southeast-3.amazonaws.com
    ca-central-1:
      repository: 602401143452.dkr.ecr.ca-central-1.amazonaws.com
    cn-north-1:
      repository: 918309763551.dkr.ecr.cn-north-1.amazonaws.com.cn
    cn-northwest-1:
      repository: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn
    eu-central-1:
      repository: 602401143452.dkr.ecr.eu-central-1.amazonaws.com
    eu-north-1:
      repository: 602401143452.dkr.ecr.eu-north-1.amazonaws.com
    eu-south-1:
      repository: 590381155156.dkr.ecr.eu-south-1.amazonaws.com
    eu-west-1:
      repository: 602401143452.dkr.ecr.eu-west-1.amazonaws.com
    eu-west-2:
      repository: 602401143452.dkr.ecr.eu-west-2.amazonaws.com
    eu-west-3:
      repository: 602401143452.dkr.ecr.eu-west-3.amazonaws.com
    me-south-1:
      repository: 558608220178.dkr.ecr.me-south-1.amazonaws.com
    me-central-1:
      repository: 759879836304.dkr.ecr.me-central-1.amazonaws.com
    sa-east-1:
      repository: 602401143452.dkr.ecr.sa-east-1.amazonaws.com
    us-east-1:
      repository: 602401143452.dkr.ecr.us-east-1.amazonaws.com
    us-east-2:
      repository: 602401143452.dkr.ecr.us-east-2.amazonaws.com
    us-gov-east-1:
      repository: 151742754352.dkr.ecr.us-gov-east-1.amazonaws.com
    us-gov-west-1:
      repository: 013241004608.dkr.ecr.us-gov-west-1.amazonaws.com
    us-west-1:
      repository: 602401143452.dkr.ecr.us-west-1.amazonaws.com
    us-west-2:
      repository: 602401143452.dkr.ecr.us-west-2.amazonaws.com

Resources:
  EfsCsiDriverrRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref ClusterOidcProvider
            Action:
              - "sts:AssumeRoleWithWebIdentity"
      Path: /
      Policies:
        - PolicyName: AmazonEKS_EFS_CSI_Driver_Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - elasticfilesystem:DescribeAccessPoints
              - elasticfilesystem:DescribeFileSystems
              - elasticfilesystem:DescribeMountTargets
              - ec2:DescribeAvailabilityZones
              Resource: "*"
            - Effect: Allow
              Action:
              - elasticfilesystem:CreateAccessPoint
              Resource: "*"
              Condition:
                StringLike:
                  aws:RequestTag/efs.csi.aws.com/cluster: 'true'
            - Effect: Allow
              Action: elasticfilesystem:DeleteAccessPoint
              Resource: "*"
              Condition:
                StringEquals:
                  aws:ResourceTag/efs.csi.aws.com/cluster: 'true'
      RoleName: !If
        - UseEfsCsiDriverRoleName
        - !Ref EfsCsiDriverRoleName
        - !Sub "${ClusterName}-efs-csi-driver-role"
      Tags:
        - Key: Name
          Value: !If
            - UseEfsCsiDriverRoleName
            - !Ref EfsCsiDriverRoleName
            - !Sub "${ClusterName}-efs-csi-driver-role"
        - Key: project
          Value: !Ref ProjectName

  EfsCsiDriverrRoleConfig:
    Type: Custom::ServiceAccountRoleConfig
    Properties:
      ServiceToken: !Ref ServiceAccountRoleConfigArn
      RoleName: !Ref EfsCsiDriverrRole
      OidcIssuerUrl: !Ref ClusterOidcIssuerUrl
      OidcArn: !Ref ClusterOidcProvider
      Namespace: kube-system
      ServiceAccount: efs-csi-controller-sa

  EfsCsiDriverHelmChart:
    Type: AWSQS::Kubernetes::Helm
    DependsOn: EfsCsiDriverrRoleConfig
    Properties:
      ClusterID: !Ref ClusterName
      Name: aws-efs-csi-driver
      Namespace: kube-system
      Repository: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
      Chart: aws-efs-csi-driver/aws-efs-csi-driver
      ValueYaml: !Sub
        - |
          image:
            repository: ${repository}/eks/aws-efs-csi-driver
          controller:
            serviceAccount:
              annotations:
                eks.amazonaws.com/role-arn: ${efs_csi_driver_role}
        - repository: !FindInMap [EfsCsiDriverRepositoryMap, !Ref AWS::Region, repository]
          efs_csi_driver_role: !GetAtt EfsCsiDriverrRole.Arn